### ISSUE TITLE
Would it be possible to set BORG_PASSPHRASE per-process instead of in the same process?

### ISSUE THREAD

**Issue by dpbriggs** [myOmikron/borgbackup#1]
Hi, thanks for making such a great crate. I'm planning on using this to start several borg backups in parallel but I'm concerned about some bugs related [to this line](https://github.com/myOmikron/borgbackup/blob/910e9847954bda7d998d447df53a65b7a69247c3/src/asynchronous/create.rs#L30). Would it be possible to use the [env method](https://docs.rs/tokio/latest/tokio/process/struct.Command.html#method.env) instead?

If you would prefer I could make a PR to save some hassle.

**Comment by myOmikron** [comment]
Sounds reasonable, I wasn't happy with it either, cause the variable could leak, if the process returned an `Err`.
